language: erlang
sudo: required
notifications:
  email: false
otp_release:
  - 19.0
  - 19.3
  - 20.0
  - 20.1
  - 20.3
  - 21.0
  - 21.2
  - 21.3
  - 22.0
  - 22.1
  - 22.2
  - 22.3
  - 23.0
services:
  - redis-server
script: make check test
