---
name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: Run checks and tests over ${{matrix.otp_vsn}}, ${{matrix.redis_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    services:
      redis:
        image: ${{matrix.redis_vsn}}
        ports:
          - 127.0.0.1:6379:6379/tcp
    strategy:
      matrix:
        otp_vsn: [19.3.6.13, 20.3.8.26, 21.3.8.17, 22.3.4.9, 23.1.5]
        os: [ubuntu-latest]
        redis_vsn:
          - redis:4
          - redis:5
          - redis:6
    steps:
      - uses: actions/checkout@v2
      - uses: gleam-lang/setup-erlang@v1.0.0
        with:
          otp-version: ${{matrix.otp_vsn}}
      - run: make version
