---
name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: Run checks and tests over ${{matrix.otp_vsn}}, ${{matrix.redis_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    services:
      redis:
        image: ${{matrix.redis_vsn}}
        ports:
          - 127.0.0.1:6379:6379/tcp
    strategy:
      matrix:
        otp_vsn: [22, 23, 24]
        os: [ubuntu-18.04]
        redis_vsn:
          - redis:4
          - redis:5
          - redis:6
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        id: setup-beam
        with:
          otp-version: ${{matrix.otp_vsn}}
          rebar3-version: '3.16'
      - name: restore _build
        uses: actions/cache@v2
        with:
          path: _build
          key: _build-cache-for-os-${{runner.os}}-otp-${{steps.setup-beam.outputs.otp-version}}-rebar3-${{steps.setup-beam.outputs.rebar3-version}}-hash-${{hashFiles('rebar.lock')}}
      - name: restore rebar3's cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/rebar3
          key: rebar3-cache-for-os-${{runner.os}}-otp-${{steps.setup-beam.outputs.otp-version}}-rebar3-${{steps.setup-beam.outputs.rebar3-version}}-hash-${{hashFiles('rebar.lock')}}
      - run: make version
